# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/calculadora.proto
# Protobuf Python Version: 7.36.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    36,
    0,
    '',
    'proto/calculadora.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17proto/calculadora.proto\x12\x0b\x63\x61lculadora\"T\n\nRequisicao\x12\x0e\n\x06numero\x18\x01 \x01(\x05\x12\x11\n\toperando1\x18\x02 \x01(\x01\x12\x10\n\x08operacao\x18\x03 \x01(\t\x12\x11\n\toperando2\x18\x04 \x01(\x01\"L\n\x08Resposta\x12\x0e\n\x06numero\x18\x01 \x01(\x05\x12\x0f\n\x07sucesso\x18\x02 \x01(\x08\x12\x11\n\tresultado\x18\x03 \x01(\x01\x12\x0c\n\x04\x65rro\x18\x04 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REQUISICAO']._serialized_start=40
  _globals['_REQUISICAO']._serialized_end=124
  _globals['_RESPOSTA']._serialized_start=126
  _globals['_RESPOSTA']._serialized_end=202
# @@protoc_insertion_point(module_scope)
